import type { ServiceName } from "@faiber/sdk-core";

export type FaiberTransport = "rest" | "multipart" | "sse" | "websocket" | "udp" | "sandbox-proxy";

/** Machine-readable service guidance intended for humans, IDEs, and coding agents. */
export interface FaiberServiceCapability {
  readonly service: ServiceName;
  readonly title: string;
  readonly description: string;
  readonly aiGuidance: string;
  readonly transports: readonly FaiberTransport[];
  readonly operationCount: number;
  readonly environmentVariable: string;
  readonly auth: string;
}

/**
 * Complete sandbox service catalog. Agents should choose the narrow typed facade property first,
 * then `sdk.<service>.operations` for generated route-complete APIs. The internal sandbox
 * management gateway is intentionally not part of the public SDK contract.
 */
export const FAIBER_SERVICE_CAPABILITIES = [
  { service: "idp", title: "Identity", description: "Authentication, sessions, users, roles, permissions, OAuth, OIDC, and access control.", aiGuidance: "Authenticate and manage identity here; never store credentials in generated project code.", transports: ["rest"], operationCount: 97, environmentVariable: "FAIBER_IDP_URL", auth: "Public bootstrap plus Bearer/cookie and permission-guarded administration." },
  { service: "profile", title: "Profiles", description: "Profiles, typed properties, locations, avatars, surveys, metadata, and profile media.", aiGuidance: "Use self-address routes for checkout and atomic profile patch inputs elsewhere; preserve omitted versus null field semantics.", transports: ["rest", "multipart"], operationCount: 174, environmentVariable: "FAIBER_PROFILE_URL", auth: "IDP Bearer token or secure session cookie." },
  { service: "modules", title: "Content and commerce", description: "Products, posts, pages, taxonomy, SEO, media, inventory, orders, comments, reactions, authors, settings, and governed Agentic proposals.", aiGuidance: "Prefer the curated resource APIs; use operations for capability-specific routes and exact queries.", transports: ["rest", "multipart"], operationCount: 171, environmentVariable: "FAIBER_MODULES_URL", auth: "IDP Bearer token or secure session cookie; write routes may require permissions." },
  { service: "asset", title: "Assets and billing", description: "Wallets, balances, plans, subscriptions, ranks, ledger, AI usage plans, badges, history, leaderboard, and sandbox billing.", aiGuidance: "Treat financial responses as authoritative and use idempotent backend flows for mutations.", transports: ["rest"], operationCount: 86, environmentVariable: "FAIBER_ASSET_URL", auth: "IDP Bearer token or secure session cookie; admin routes declare permissions." },
  { service: "payment", title: "Payments", description: "Gateway and settings administration, payment creation, verification and rejection logs, callbacks, income reporting, and transaction status.", aiGuidance: "Do not infer payment success; verify against returned transaction status and retain provider callback and verification evidence.", transports: ["rest"], operationCount: 23, environmentVariable: "FAIBER_PAYMENT_URL", auth: "Public callbacks where defined; otherwise IDP session and permissions." },
  { service: "messenger", title: "Messaging delivery", description: "Notification inbox and read state, realtime delivery, templates and localized content, channels, providers, dashboards, and integrations.", aiGuidance: "Use templates for reusable communication, use realtime auth only for the current identity, and never embed provider secrets client-side.", transports: ["rest"], operationCount: 36, environmentVariable: "FAIBER_MESSENGER_URL", auth: "IDP session; administrative operations are permission guarded." },
  { service: "crm", title: "CRM", description: "Workspace, member workflows, workflow nodes, daily quotas and statistics, pipelines, boards, companies, contacts, leads, SOS, reminders, tasks, activities, worklogs, reports, automation, and Agentic insights.", aiGuidance: "Use server-authoritative dashboard statistics, preserve optimistic versions and idempotency keys, and configure tenant workflows and nodes through API operations rather than package seed data.", transports: ["rest"], operationCount: 90, environmentVariable: "FAIBER_CRM_URL", auth: "IDP session with capability-specific CRM permissions; crm:admin is the service-wide override." },
  { service: "lms", title: "Learning", description: "Courses, classrooms, homework banks and items, homework/project assignments, exam banks and items, exam sessions and users, certificates, and reports.", aiGuidance: "Keep reusable bank definitions separate from assignment/session delivery records, preserve UUID ownership, and honor classroom-session lock state before opening provisioned Session rooms.", transports: ["rest"], operationCount: 164, environmentVariable: "FAIBER_LMS_URL", auth: "IDP session with learner context or capability-specific LMS read, create, update, and delete permissions." },
  { service: "reservation", title: "Reservations", description: "Bookable services, providers, schedules, slots, and reservations.", aiGuidance: "Fetch current availability before booking and handle backend conflicts as expected contention.", transports: ["rest"], operationCount: 29, environmentVariable: "FAIBER_RESERVATION_URL", auth: "IDP Bearer token or secure session cookie." },
  { service: "session", title: "Live sessions", description: "Room lifecycle and interactive delivery, access tokens, participant views, playback and recording views, recording scheduling and manifests, branding, analytics, and integrations.", aiGuidance: "Request short-lived room access from the service, use canonical view URL helpers, and never synthesize media access tokens or recording manifests.", transports: ["rest"], operationCount: 35, environmentVariable: "FAIBER_SESSION_URL", auth: "IDP session with room permissions for management operations." },
  { service: "version", title: "Service versions", description: "Service registry, current releases, release history, health, and OpenAPI discovery.", aiGuidance: "Use this service to inspect platform compatibility; do not hardcode deployment versions.", transports: ["rest"], operationCount: 6, environmentVariable: "FAIBER_VERSION_URL", auth: "Public or deployment-defined IDP session." },
  { service: "flow", title: "Automation", description: "Automations, triggers, actions, validation, imports, runs, and execution history.", aiGuidance: "Validate flows before execution and use run identifiers to inspect asynchronous outcomes.", transports: ["rest"], operationCount: 18, environmentVariable: "FAIBER_FLOW_URL", auth: "IDP Bearer token or secure session cookie." },
  { service: "knowledge", title: "Knowledge", description: "Knowledge bases, groups, items, graph edges, chat bindings, rules, runtime resolution, and actions.", aiGuidance: "Use runtime endpoints for published knowledge and management endpoints for authoring.", transports: ["rest"], operationCount: 37, environmentVariable: "FAIBER_KNOWLEDGE_URL", auth: "IDP session with read/write/publish/runtime permissions." },
  { service: "chat", title: "Chat", description: "Assistant catalog and administration, direct/group/channel/AI conversations, members, messages, attachments, reactions, runtime inputs, read state, SSE, and realtime authorization.", aiGuidance: "Use server conversation/message identifiers, complete attachment uploads, and follow the service's runtime-input and streaming/realtime contracts.", transports: ["rest", "sse"], operationCount: 35, environmentVariable: "FAIBER_CHAT_URL", auth: "IDP session with chat read/write/manage/AI permissions." },
  { service: "social", title: "Social", description: "Feeds, posts, comments, reactions, bookmarks, claims, capability policies, funding events, reports, analytics, and moderation.", aiGuidance: "Use self-service routes for a user's content and moderation routes only with explicit permissions.", transports: ["rest", "multipart"], operationCount: 61, environmentVariable: "FAIBER_SOCIAL_URL", auth: "IDP session with social write or moderation permissions." },
  { service: "state", title: "Realtime state", description: "Worlds, rooms, endpoints, authoritative state, WebSocket/UDP replication, prediction, and WASM simulation.", aiGuidance: "Create/join through REST, then use the returned short-lived ticket with StateRealtimeClient.", transports: ["rest", "websocket", "udp"], operationCount: 24, environmentVariable: "FAIBER_STATE_URL", auth: "IDP session for REST; signed join ticket for realtime transports." },
  { service: "drm", title: "Digital media", description: "DRM dashboard and statuses, media and multipart uploads, folders and tags, content libraries and categories, compositions, mixed media, workflows, manifests, packaging, analysis, audit, and operations settings.", aiGuidance: "Use multipart or chunked binary uploads as appropriate, preserve library/composition workflows, and request short-lived playback or ClearKey material only when needed.", transports: ["rest", "multipart"], operationCount: 96, environmentVariable: "FAIBER_DRM_URL", auth: "IDP session with resource-specific drm:* permissions; playback and license material are short lived." },
  { service: "task", title: "Tasks", description: "Projects, scoped grants, work items, comments, sprints, reports, agent proposals, health, discovery, and realtime invalidations.", aiGuidance: "Use Task as the sole generic work authority; preserve scoped grants, idempotency keys, optimistic versions, and approval boundaries.", transports: ["rest", "sse"], operationCount: 58, environmentVariable: "FAIBER_TASK_URL", auth: "Verified IDP identity and global Task permission plus Task-owned workspace/team/project/work-item grants." },
  { service: "manage", title: "Project management gateway", description: "Project-scoped service proxying, enabled-service discovery, image uploads, model discovery, and governed Manage Agent interactions.", aiGuidance: "Use typed service clients for known operations and execute runtime agent actions only after the user reviews mutations.", transports: ["rest", "sse", "sandbox-proxy"], operationCount: 14, environmentVariable: "FAIBER_MANAGE_URL", auth: "Agentic-minted project session in a secure HttpOnly cookie; proxy access remains project scoped." },
] as const satisfies readonly FaiberServiceCapability[];

export const FAIBER_CAPABILITY_BY_SERVICE: Readonly<Record<ServiceName, FaiberServiceCapability>> =
  Object.fromEntries(FAIBER_SERVICE_CAPABILITIES.map(capability => [capability.service, capability])) as unknown as Record<ServiceName, FaiberServiceCapability>;

/** Returns machine-readable usage guidance for one service or the complete platform catalog. */
export function describeFaiber(service?: ServiceName): FaiberServiceCapability | readonly FaiberServiceCapability[] {
  return service ? FAIBER_CAPABILITY_BY_SERVICE[service] : FAIBER_SERVICE_CAPABILITIES;
}
