import test from 'node:test';
import assert from 'node:assert/strict';
import {AxiosHeaders} from 'axios';
import {FaiberClient,MemoryTokenProvider} from '../packages/core/dist/index.js';
import {TaskApi} from '../packages/task/dist/index.js';
import {ChatApi} from '../packages/chat/dist/index.js';
import {KnowledgeApi} from '../packages/knowledge/dist/index.js';
import {ProfileApi} from '../packages/profile/dist/index.js';
test('workspace contracts, role discovery and review revisions use authenticated SDK transport',async()=>{
 const calls=[];const connection=service=>new FaiberClient(service,{domains:{[service]:`https://${service}.example.com`},tokenProvider:new MemoryTokenProvider({accessToken:'caller'}),axios:{adapter:async config=>{calls.push(config);return {data:{data:{}},status:200,statusText:'OK',headers:new AxiosHeaders(),config}}}});
 const task=new TaskApi(connection('task'));
 await task.workspaceAssistant.query({owner_id:'caller',completed_by_me:true,limit:200});
 await task.workspaceAssistant.propose({conversation_id:'conversation',project_id:null,request_id:'once',operations:[{kind:'delete',id:'record',expected_version:2}]});
 await task.workspaceAssistant.apply('proposal',3);await task.workspaceAssistant.refresh('proposal',3);
 await new ChatApi(connection('chat')).workspaceAssistant.roles();
 await new KnowledgeApi(connection('knowledge')).assistantContracts('assistant','2done-action');
 await new ProfileApi(connection('profile')).resolvePeople({user_ids:['member']});
 assert.ok(calls.every(c=>c.headers.get('Authorization')==='Bearer caller'));
 assert.equal(calls[2].headers.get('If-Match'),'3');assert.equal(calls[3].headers.get('If-Match'),'3');
 assert.deepEqual(calls.map(c=>[c.method,c.url]),[['post','/api/v1/assistant/query'],['post','/api/v1/review-proposals'],['post','/api/v1/review-proposals/proposal/apply'],['post','/api/v1/review-proposals/proposal/refresh'],['get','/api/v1/workspace-assistants'],['get','/api/v1/runtime/assistants/assistant/contracts/2done-action'],['post','/api/v1/profile/people/resolve']]);
 assert.deepEqual(JSON.parse(calls[0].data),{owner_id:'caller',completed_by_me:true,limit:200});
});
