import type { QualityProfile } from "./quality.js";
export type RendererKind="webgpu"|"webgl2"|"headless";
export interface RenderFrame{alpha:number;time:number}
export interface Renderer{readonly kind:RendererKind;initialize(canvas:HTMLCanvasElement,quality:QualityProfile):Promise<void>;resize(width:number,height:number,pixelRatio:number):void;render(frame:RenderFrame):void;dispose():void}
export type RendererFactory=(kind:RendererKind)=>Renderer;
export function chooseRenderer(profile:QualityProfile,preferred?:RendererKind):RendererKind{if(preferred==="headless")return preferred;if(preferred==="webgpu"&&profile.capabilities.webgpu)return preferred;if(preferred==="webgl2"&&profile.capabilities.webgl2)return preferred;if(profile.capabilities.webgpu)return"webgpu";if(profile.capabilities.webgl2)return"webgl2";return"headless"}
export class WebGl2Renderer implements Renderer{readonly kind="webgl2";private gl:WebGL2RenderingContext|undefined;async initialize(canvas:HTMLCanvasElement,quality:QualityProfile){const gl=canvas.getContext("webgl2",{antialias:quality.features.antiAliasing==="msaa4",powerPreference:quality.tier==="low"?"low-power":"high-performance"});if(!gl)throw new Error("WebGL 2 is unavailable");this.gl=gl}resize(width:number,height:number,pixelRatio:number){if(this.gl)this.gl.viewport(0,0,Math.floor(width*pixelRatio),Math.floor(height*pixelRatio))}render(){this.gl?.clear(this.gl.COLOR_BUFFER_BIT|this.gl.DEPTH_BUFFER_BIT)}dispose(){this.gl=undefined}}
type GpuDevice={queue:{submit(commands:unknown[]):void};createCommandEncoder():{beginRenderPass(descriptor:unknown):{end():void};finish():unknown}};
type GpuContext={configure(options:unknown):void;getCurrentTexture():{createView():unknown}};
type GpuNavigator=Navigator&{gpu?:{requestAdapter(options?:unknown):Promise<{requestDevice():Promise<GpuDevice>}|null>;getPreferredCanvasFormat():string}};
export class WebGpuRenderer implements Renderer{readonly kind="webgpu";private device:GpuDevice|undefined;private context:GpuContext|undefined;async initialize(canvas:HTMLCanvasElement,quality:QualityProfile){const gpu=(navigator as GpuNavigator).gpu;if(!gpu)throw new Error("WebGPU is unavailable");const adapter=await gpu.requestAdapter({powerPreference:quality.tier==="low"?"low-power":"high-performance"});if(!adapter)throw new Error("No WebGPU adapter is available");this.device=await adapter.requestDevice();this.context=canvas.getContext("webgpu") as unknown as GpuContext;this.context.configure({device:this.device,format:gpu.getPreferredCanvasFormat(),alphaMode:"premultiplied"})}resize(){}render(){if(!this.device||!this.context)return;const encoder=this.device.createCommandEncoder();const pass=encoder.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),clearValue:{r:.015,g:.025,b:.06,a:1},loadOp:"clear",storeOp:"store"}]});pass.end();this.device.queue.submit([encoder.finish()])}dispose(){this.device=undefined;this.context=undefined}}
export class HeadlessRenderer implements Renderer{readonly kind="headless";async initialize(){}resize(){}render(){}dispose(){}}
